// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using System.Diagnostics;
    using System.Net;
    using System.Net.Http;
    using System.Net.Http.Headers;
    using System.Text;
    using System.Text.RegularExpressions;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;
    using Newtonsoft.Json;
    using Models;

    public partial class ESawClient : ServiceClient<ESawClient>, IESawClient
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        public JsonSerializerSettings SerializationSettings { get; private set; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        public JsonSerializerSettings DeserializationSettings { get; private set; }        

        /// <summary>
        /// Subscription credentials which uniquely identify client subscription.
        /// </summary>
        public ServiceClientCredentials Credentials { get; private set; }

        /// <summary>
        /// Gets the IAuthorization.
        /// </summary>
        public virtual IAuthorization Authorization { get; private set; }

        /// <summary>
        /// Gets the IEnvelope.
        /// </summary>
        public virtual IEnvelope Envelope { get; private set; }

        /// <summary>
        /// Gets the IRecipient.
        /// </summary>
        public virtual IRecipient Recipient { get; private set; }

        /// <summary>
        /// Gets the ISspFile.
        /// </summary>
        public virtual ISspFile SspFile { get; private set; }

        /// <summary>
        /// Gets the ITeam.
        /// </summary>
        public virtual ITeam Team { get; private set; }

        /// <summary>
        /// Gets the IUser.
        /// </summary>
        public virtual IUser User { get; private set; }

        /// <summary>
        /// Gets the IVersion.
        /// </summary>
        public virtual IVersion Version { get; private set; }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        protected ESawClient(params DelegatingHandler[] handlers) : base(handlers)
        {
            this.Initialize();
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        protected ESawClient(HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : base(rootHandler, handlers)
        {
            this.Initialize();
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        protected ESawClient(Uri baseUri, params DelegatingHandler[] handlers) : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this.BaseUri = baseUri;
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        protected ESawClient(Uri baseUri, HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : this(rootHandler, handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this.BaseUri = baseUri;
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Subscription credentials which uniquely identify client subscription.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        public ESawClient(ServiceClientCredentials credentials, params DelegatingHandler[] handlers) : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this.Credentials = credentials;
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Subscription credentials which uniquely identify client subscription.
        /// </param>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        public ESawClient(ServiceClientCredentials credentials, HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : this(rootHandler, handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this.Credentials = credentials;
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Subscription credentials which uniquely identify client subscription.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        public ESawClient(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers) : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this.BaseUri = baseUri;
            this.Credentials = credentials;
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }

        /// <summary>
        /// Initializes a new instance of the ESawClient class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Subscription credentials which uniquely identify client subscription.
        /// </param>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The delegating handlers to add to the http client pipeline.
        /// </param>
        public ESawClient(Uri baseUri, ServiceClientCredentials credentials, HttpClientHandler rootHandler, params DelegatingHandler[] handlers) : this(rootHandler, handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this.BaseUri = baseUri;
            this.Credentials = credentials;
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }

        /// <summary>
        /// An optional partial-method to perform custom initialization.
        ///</summary> 
        partial void CustomInitialize();
        /// <summary>
        /// Initializes client properties.
        /// </summary>
        private void Initialize()
        {
            this.Authorization = new Authorization(this);
            this.Envelope = new Envelope(this);
            this.Recipient = new Recipient(this);
            this.SspFile = new SspFile(this);
            this.Team = new Team(this);
            this.User = new User(this);
            this.Version = new Version(this);
            this.BaseUri = new Uri("http://beta3.testlab.xyzmo.com/eSignAnyWhere/api");
            SerializationSettings = new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                ContractResolver = new ReadOnlyJsonContractResolver(),
                Converters = new List<JsonConverter>
                    {
                        new Iso8601TimeSpanConverter()
                    }
            };
            DeserializationSettings = new JsonSerializerSettings
            {
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                ContractResolver = new ReadOnlyJsonContractResolver(),
                Converters = new List<JsonConverter>
                    {
                        new Iso8601TimeSpanConverter()
                    }
            };
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiAuthenticationMethod>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiAuthenticationMethod>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiWorkstepTask>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiWorkstepTask>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiAddFormFieldDescriptor>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiAddFormFieldDescriptor>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiFillFormDescriptor>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiFillFormDescriptor>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiSigType>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiSigType>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiForm>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiForm>("DiscriminatorType"));
            SerializationSettings.Converters.Add(new PolymorphicSerializeJsonConverter<FlowApiFormFieldValidation>("DiscriminatorType"));
            DeserializationSettings.Converters.Add(new PolymorphicDeserializeJsonConverter<FlowApiFormFieldValidation>("DiscriminatorType"));
            CustomInitialize();
        }    
    }
}
