// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DraftCreateModel
    {
        /// <summary>
        /// Initializes a new instance of the DraftCreateModel class.
        /// </summary>
        public DraftCreateModel() { }

        /// <summary>
        /// Initializes a new instance of the DraftCreateModel class.
        /// </summary>
        public DraftCreateModel(IList<string> sspFileIds = default(IList<string>), FlowApiSendEnvelopeDescription flowApiSendEnvelopeDescription = default(FlowApiSendEnvelopeDescription), FlowApiCreateDraftOptions flowApiCreateDraftOptions = default(FlowApiCreateDraftOptions))
        {
            SspFileIds = sspFileIds;
            FlowApiSendEnvelopeDescription = flowApiSendEnvelopeDescription;
            FlowApiCreateDraftOptions = flowApiCreateDraftOptions;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SspFileIds")]
        public IList<string> SspFileIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiSendEnvelopeDescription")]
        public FlowApiSendEnvelopeDescription FlowApiSendEnvelopeDescription { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiCreateDraftOptions")]
        public FlowApiCreateDraftOptions FlowApiCreateDraftOptions { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (this.FlowApiSendEnvelopeDescription != null)
            {
                this.FlowApiSendEnvelopeDescription.Validate();
            }
        }
    }
}
