// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Model for sending envelopes.
    /// </summary>
    public partial class EnvelopeSendModel
    {
        /// <summary>
        /// Initializes a new instance of the EnvelopeSendModel class.
        /// </summary>
        public EnvelopeSendModel() { }

        /// <summary>
        /// Initializes a new instance of the EnvelopeSendModel class.
        /// </summary>
        public EnvelopeSendModel(IList<string> sspFileIds, FlowApiSendEnvelopeDescription flowApiSendEnvelopeDescription)
        {
            SspFileIds = sspFileIds;
            FlowApiSendEnvelopeDescription = flowApiSendEnvelopeDescription;
        }

        /// <summary>
        /// The ids of uploaded files.
        /// </summary>
        [JsonProperty(PropertyName = "SspFileIds")]
        public IList<string> SspFileIds { get; set; }

        /// <summary>
        /// The description of the envelope.
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiSendEnvelopeDescription")]
        public FlowApiSendEnvelopeDescription FlowApiSendEnvelopeDescription { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (SspFileIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SspFileIds");
            }
            if (FlowApiSendEnvelopeDescription == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "FlowApiSendEnvelopeDescription");
            }
            if (this.FlowApiSendEnvelopeDescription != null)
            {
                this.FlowApiSendEnvelopeDescription.Validate();
            }
        }
    }
}
