// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Description for sending an envelope from a template.
    /// </summary>
    public partial class EnvelopeSendFromTemplateModel
    {
        /// <summary>
        /// Initializes a new instance of the EnvelopeSendFromTemplateModel
        /// class.
        /// </summary>
        public EnvelopeSendFromTemplateModel() { }

        /// <summary>
        /// Initializes a new instance of the EnvelopeSendFromTemplateModel
        /// class.
        /// </summary>
        public EnvelopeSendFromTemplateModel(string templateId = default(string), FlowApiEnvelopeOverrideOptions flowApiEnvelopeOverrideOptions = default(FlowApiEnvelopeOverrideOptions))
        {
            TemplateId = templateId;
            FlowApiEnvelopeOverrideOptions = flowApiEnvelopeOverrideOptions;
        }

        /// <summary>
        /// The Id of the template.
        /// </summary>
        [JsonProperty(PropertyName = "TemplateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// Options which should be overriden for teh template.
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiEnvelopeOverrideOptions")]
        public FlowApiEnvelopeOverrideOptions FlowApiEnvelopeOverrideOptions { get; set; }

    }
}
