// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class EnvelopePrepareModel
    {
        /// <summary>
        /// Initializes a new instance of the EnvelopePrepareModel class.
        /// </summary>
        public EnvelopePrepareModel() { }

        /// <summary>
        /// Initializes a new instance of the EnvelopePrepareModel class.
        /// </summary>
        public EnvelopePrepareModel(IList<string> sspFileIds = default(IList<string>), FlowApiAdHocWorkstepConfiguration flowApiAdHocWorkstepConfiguration = default(FlowApiAdHocWorkstepConfiguration), FlowApiPrepareSendEnvelopeStepsDescriptor flowApiPrepareSendEnvelopeStepsDescriptor = default(FlowApiPrepareSendEnvelopeStepsDescriptor))
        {
            SspFileIds = sspFileIds;
            FlowApiAdHocWorkstepConfiguration = flowApiAdHocWorkstepConfiguration;
            FlowApiPrepareSendEnvelopeStepsDescriptor = flowApiPrepareSendEnvelopeStepsDescriptor;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SspFileIds")]
        public IList<string> SspFileIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiAdHocWorkstepConfiguration")]
        public FlowApiAdHocWorkstepConfiguration FlowApiAdHocWorkstepConfiguration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FlowApiPrepareSendEnvelopeStepsDescriptor")]
        public FlowApiPrepareSendEnvelopeStepsDescriptor FlowApiPrepareSendEnvelopeStepsDescriptor { get; set; }

    }
}
