// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A step in an envelope representing recipients.
    /// </summary>
    public partial class FlowApiSendEnvelopeStep
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSendEnvelopeStep class.
        /// </summary>
        public FlowApiSendEnvelopeStep() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSendEnvelopeStep class.
        /// </summary>
        public FlowApiSendEnvelopeStep(int orderIndex, IList<FlowApiSendEnvelopeRecipient> recipients, string emailBodyExtra = default(string), string recipientType = default(string), FlowApiWorkstepConfiguration workstepConfiguration = default(FlowApiWorkstepConfiguration), IList<FlowApiSendEnvelopeDocumentOption> documentOptions = default(IList<FlowApiSendEnvelopeDocumentOption>))
        {
            OrderIndex = orderIndex;
            Recipients = recipients;
            EmailBodyExtra = emailBodyExtra;
            RecipientType = recipientType;
            WorkstepConfiguration = workstepConfiguration;
            DocumentOptions = documentOptions;
        }

        /// <summary>
        /// The order index of the step.
        /// </summary>
        [JsonProperty(PropertyName = "OrderIndex")]
        public int OrderIndex { get; set; }

        /// <summary>
        /// A list of recipients for this step (usally 1, multiple for bulk).
        /// </summary>
        [JsonProperty(PropertyName = "Recipients")]
        public IList<FlowApiSendEnvelopeRecipient> Recipients { get; set; }

        /// <summary>
        /// The additional email body for the step.
        /// </summary>
        [JsonProperty(PropertyName = "EmailBodyExtra")]
        public string EmailBodyExtra { get; set; }

        /// <summary>
        /// The recipient type of the step. Possible values include: 'Signer',
        /// 'Cc', 'Acknowledge', 'Pkcs7Signer'
        /// </summary>
        [JsonProperty(PropertyName = "RecipientType")]
        public string RecipientType { get; set; }

        /// <summary>
        /// The configuration for the step.
        /// Only necessary for &lt;code&gt;RecipientType&lt;/code&gt; Signer
        /// and Pkcs7Signer.
        /// </summary>
        [JsonProperty(PropertyName = "WorkstepConfiguration")]
        public FlowApiWorkstepConfiguration WorkstepConfiguration { get; set; }

        /// <summary>
        /// The document options for the step.
        /// </summary>
        [JsonProperty(PropertyName = "DocumentOptions")]
        public IList<FlowApiSendEnvelopeDocumentOption> DocumentOptions { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Recipients == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Recipients");
            }
            if (this.Recipients != null)
            {
                foreach (var element in this.Recipients)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
