// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The authentication filter.
    /// </summary>
    public partial class FlowApiSendEnvelopeAuthenticationFilter
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSendEnvelopeAuthenticationFilter class.
        /// </summary>
        public FlowApiSendEnvelopeAuthenticationFilter() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSendEnvelopeAuthenticationFilter class.
        /// </summary>
        public FlowApiSendEnvelopeAuthenticationFilter(string compareOperation = default(string), string filterId = default(string), string filterValue = default(string))
        {
            CompareOperation = compareOperation;
            FilterId = filterId;
            FilterValue = filterValue;
        }

        /// <summary>
        /// The compare method of the filter. Possible values include: 'Equals'
        /// </summary>
        [JsonProperty(PropertyName = "CompareOperation")]
        public string CompareOperation { get; set; }

        /// <summary>
        /// The filter id of the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "FilterId")]
        public string FilterId { get; set; }

        /// <summary>
        /// The filter value of the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "FilterValue")]
        public string FilterValue { get; set; }

    }
}
