// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Flow Api error.
    /// </summary>
    public partial class FlowApiError
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiError class.
        /// </summary>
        public FlowApiError() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiError class.
        /// </summary>
        public FlowApiError(string errorId = default(string), string message = default(string), string supportId = default(string), object thrownException = default(object))
        {
            ErrorId = errorId;
            Message = message;
            SupportId = supportId;
            ThrownException = thrownException;
        }

        /// <summary>
        /// Id of the error.
        /// </summary>
        [JsonProperty(PropertyName = "ErrorId")]
        public string ErrorId { get; set; }

        /// <summary>
        /// Message from the error.
        /// </summary>
        [JsonProperty(PropertyName = "Message")]
        public string Message { get; set; }

        /// <summary>
        /// Support identifier.
        /// </summary>
        [JsonProperty(PropertyName = "SupportId")]
        public string SupportId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ThrownException")]
        public object ThrownException { get; set; }

    }
}
