// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Base class for FormFieldValidation.
    /// </summary>
    public partial class FlowApiFormFieldValidation
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFormFieldValidation class.
        /// </summary>
        public FlowApiFormFieldValidation() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFormFieldValidation class.
        /// </summary>
        public FlowApiFormFieldValidation(string type = default(string))
        {
            Type = type;
        }

        /// <summary>
        /// Type of FormFieldValidation. Possible values include: 'None',
        /// 'Date', 'Email', 'Number', 'Phone', 'Time'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

    }
}
