// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The description of the form field which should be filled.
    /// </summary>
    public partial class FlowApiFillFormDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFillFormDescriptor class.
        /// </summary>
        public FlowApiFillFormDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFillFormDescriptor class.
        /// </summary>
        public FlowApiFillFormDescriptor(string name = default(string), string type = default(string))
        {
            Name = name;
            Type = type;
        }

        /// <summary>
        /// The name of the form field.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// Possible values include: 'TextBox', 'RadioButton', 'CheckBox',
        /// 'ListBox', 'ComboBox'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

    }
}
