// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// BiometricSignatureAndDisposableCertificateEnroll SigType. (Not yet
    /// implemented)
    /// </summary>
    public partial class FlowApiSigTypeBiometricSignatureAndDisposableCertificateEnroll : FlowApiSigType
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSigTypeBiometricSignatureAndDisposableCertificateEnroll
        /// class.
        /// </summary>
        public FlowApiSigTypeBiometricSignatureAndDisposableCertificateEnroll() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSigTypeBiometricSignatureAndDisposableCertificateEnroll
        /// class.
        /// </summary>
        public FlowApiSigTypeBiometricSignatureAndDisposableCertificateEnroll(string id = default(string), string type = default(string), bool? preferred = default(bool?))
            : base(id, type, preferred)
        {
        }

    }
}
