// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Configure a PdfSignatureCryptographicData.
    /// </summary>
    public partial class FlowApiPdfSignatureCryptographicData
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiPdfSignatureCryptographicData class.
        /// </summary>
        public FlowApiPdfSignatureCryptographicData() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiPdfSignatureCryptographicData class.
        /// </summary>
        public FlowApiPdfSignatureCryptographicData(string signatureHashAlgorithm = default(string), FlowApiSigningCertificateDescriptor signingCertificateDescriptor = default(FlowApiSigningCertificateDescriptor))
        {
            SignatureHashAlgorithm = signatureHashAlgorithm;
            SigningCertificateDescriptor = signingCertificateDescriptor;
        }

        /// <summary>
        /// Define the HashAlgorithm for the signature. Possible values
        /// include: 'Sha1', 'Sha256', 'Sha512'
        /// </summary>
        [JsonProperty(PropertyName = "SignatureHashAlgorithm")]
        public string SignatureHashAlgorithm { get; set; }

        /// <summary>
        /// Configure a SigningCertificateDescriptor for this object.
        /// </summary>
        [JsonProperty(PropertyName = "SigningCertificateDescriptor")]
        public FlowApiSigningCertificateDescriptor SigningCertificateDescriptor { get; set; }

    }
}
