// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// TransactionCode configurations.
    /// </summary>
    public partial class FlowApiTransactionCodeConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiTransactionCodeConfiguration class.
        /// </summary>
        public FlowApiTransactionCodeConfiguration() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiTransactionCodeConfiguration class.
        /// </summary>
        public FlowApiTransactionCodeConfiguration(string id = default(string), string hashAlgoritmIdentifier = default(string), IList<FlowApiText> texts = default(IList<FlowApiText>))
        {
            Id = id;
            HashAlgoritmIdentifier = hashAlgoritmIdentifier;
            Texts = texts;
        }

        /// <summary>
        /// Id of the transaction code.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// HashAlgorithm identifier to be used. Possible values include:
        /// 'Sha1', 'Sha256', 'Sha512'
        /// </summary>
        [JsonProperty(PropertyName = "HashAlgoritmIdentifier")]
        public string HashAlgoritmIdentifier { get; set; }

        /// <summary>
        /// Collection of all texts.
        /// </summary>
        [JsonProperty(PropertyName = "Texts")]
        public IList<FlowApiText> Texts { get; set; }

    }
}
