// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    [JsonObject("FlowPdfElementDescriptor[T]")]
    public partial class FlowPdfElementDescriptorT : FlowApiAddFormFieldDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the FlowPdfElementDescriptorT class.
        /// </summary>
        public FlowPdfElementDescriptorT() { }

        /// <summary>
        /// Initializes a new instance of the FlowPdfElementDescriptorT class.
        /// </summary>
        public FlowPdfElementDescriptorT(string name = default(string), bool? readOnlyProperty = default(bool?), bool? required = default(bool?), double? x = default(double?), double? y = default(double?), double? width = default(double?), double? height = default(double?), int? page = default(int?), string type = default(string))
            : base(name, readOnlyProperty, required, x, y, width, height, page, type)
        {
        }

    }
}
