// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiSignPkcs7 : FlowApiWorkstepTask
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSignPkcs7 class.
        /// </summary>
        public FlowApiSignPkcs7() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSignPkcs7 class.
        /// </summary>
        public FlowApiSignPkcs7(bool? isEnabled = default(bool?), bool? isCompleted = default(bool?), bool? isRequired = default(bool?), string id = default(string), string displayName = default(string), int? docRefNumber = default(int?), string additionalInformation = default(string), string completedDataTime = default(string), string batchId = default(string), string taskType = default(string), IList<FlowApiTargetDocument> targetDocuments = default(IList<FlowApiTargetDocument>))
            : base(isEnabled, isCompleted, isRequired, id, displayName, docRefNumber, additionalInformation, completedDataTime, batchId, taskType)
        {
            TargetDocuments = targetDocuments;
        }

        /// <summary>
        /// Target documents. If TargetDocuments list is empty, all documents
        /// are targeted.
        /// </summary>
        [JsonProperty(PropertyName = "TargetDocuments")]
        public IList<FlowApiTargetDocument> TargetDocuments { get; set; }

    }
}
