// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A result after uploading the file.
    /// </summary>
    public partial class FlowApiUploadSspFileResult
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiUploadSspFileResult class.
        /// </summary>
        public FlowApiUploadSspFileResult() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiUploadSspFileResult class.
        /// </summary>
        public FlowApiUploadSspFileResult(string sspFileId = default(string))
        {
            SspFileId = sspFileId;
        }

        /// <summary>
        /// The Id of the file. A &lt;code&gt;GUID&lt;/code&gt; converted to a
        /// string.
        /// </summary>
        [JsonProperty(PropertyName = "SspFileId")]
        public string SspFileId { get; set; }

    }
}
