// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines the reassignments after the deletion of a user.
    /// </summary>
    public partial class FlowApiDeleteUserReassignDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiDeleteUserReassignDescriptor class.
        /// </summary>
        public FlowApiDeleteUserReassignDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiDeleteUserReassignDescriptor class.
        /// </summary>
        public FlowApiDeleteUserReassignDescriptor(string userId, bool? reassignDrafts = default(bool?), bool? reassignTemplates = default(bool?), bool? reassignClipboard = default(bool?), bool? reassignAddressBook = default(bool?))
        {
            UserId = userId;
            ReassignDrafts = reassignDrafts;
            ReassignTemplates = reassignTemplates;
            ReassignClipboard = reassignClipboard;
            ReassignAddressBook = reassignAddressBook;
        }

        /// <summary>
        /// The id of the user which receives the assignments.
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// Reassigns drafts if true.
        /// </summary>
        [JsonProperty(PropertyName = "ReassignDrafts")]
        public bool? ReassignDrafts { get; set; }

        /// <summary>
        /// Reassigns templates if true.
        /// </summary>
        [JsonProperty(PropertyName = "ReassignTemplates")]
        public bool? ReassignTemplates { get; set; }

        /// <summary>
        /// Reassigns clipboard items if true.
        /// </summary>
        [JsonProperty(PropertyName = "ReassignClipboard")]
        public bool? ReassignClipboard { get; set; }

        /// <summary>
        /// Reassigns address book entries if true.
        /// </summary>
        [JsonProperty(PropertyName = "ReassignAddressBook")]
        public bool? ReassignAddressBook { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (UserId == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserId");
            }
        }
    }
}
