// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Configure the actions done by the server and the by the clients when
    /// the workstep is finished.
    /// </summary>
    public partial class FlowApiFinishAction
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFinishAction class.
        /// </summary>
        public FlowApiFinishAction() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFinishAction class.
        /// </summary>
        public FlowApiFinishAction(IList<FlowApiServerAction> serverActions = default(IList<FlowApiServerAction>), IList<FlowApiClientAction> clientActions = default(IList<FlowApiClientAction>))
        {
            ServerActions = serverActions;
            ClientActions = clientActions;
        }

        /// <summary>
        /// Configure the actions done by the server when the workstep is
        /// finished.
        /// </summary>
        [JsonProperty(PropertyName = "ServerActions")]
        public IList<FlowApiServerAction> ServerActions { get; private set; }

        /// <summary>
        /// Client actions can specify the behavior of a specific client after
        /// a workstep is finished.
        /// </summary>
        [JsonProperty(PropertyName = "ClientActions")]
        public IList<FlowApiClientAction> ClientActions { get; set; }

    }
}
