// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// If the workstep is not generated by hand but automatically generated
    /// by the Workstep Controller AdhocPolicies are specified
    /// </summary>
    public partial class FlowApiAdhocPolicies
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiAdhocPolicies class.
        /// </summary>
        public FlowApiAdhocPolicies() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiAdhocPolicies class.
        /// </summary>
        public FlowApiAdhocPolicies(bool? allowModificationsAfterSignature = default(bool?))
        {
            AllowModificationsAfterSignature = allowModificationsAfterSignature;
        }

        /// <summary>
        /// Allows modification after the signature.
        /// </summary>
        [JsonProperty(PropertyName = "AllowModificationsAfterSignature")]
        public bool? AllowModificationsAfterSignature { get; set; }

    }
}
