// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Rescource uris.
    /// </summary>
    public partial class FlowApiResourceUris
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiResourceUris class.
        /// </summary>
        public FlowApiResourceUris() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiResourceUris class.
        /// </summary>
        public FlowApiResourceUris(string delegationUri = default(string), string disposableCertificateDisclaimerUri = default(string), string signatureImagesUri = default(string))
        {
            DelegationUri = delegationUri;
            DisposableCertificateDisclaimerUri = disposableCertificateDisclaimerUri;
            SignatureImagesUri = signatureImagesUri;
        }

        /// <summary>
        /// Uri which will be used to retreive form data for a client.
        /// </summary>
        [JsonProperty(PropertyName = "DelegationUri")]
        public string DelegationUri { get; set; }

        /// <summary>
        /// Uri of the disposable certificate disclaimer.
        /// </summary>
        [JsonProperty(PropertyName = "DisposableCertificateDisclaimerUri")]
        public string DisposableCertificateDisclaimerUri { get; set; }

        /// <summary>
        /// Urif of the signature images.
        /// </summary>
        [JsonProperty(PropertyName = "SignatureImagesUri")]
        public string SignatureImagesUri { get; set; }

    }
}
