// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiOverrideFormFieldOptions
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiOverrideFormFieldOptions
        /// class.
        /// </summary>
        public FlowApiOverrideFormFieldOptions() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiOverrideFormFieldOptions
        /// class.
        /// </summary>
        public FlowApiOverrideFormFieldOptions(IDictionary<string, IList<FlowApiFillFormDescriptor>> forms = default(IDictionary<string, IList<FlowApiFillFormDescriptor>>))
        {
            Forms = forms;
        }

        /// <summary>
        /// A dictionary consisting of document reference number and
        /// descriptions of form fields whos value should be filled.
        /// </summary>
        [JsonProperty(PropertyName = "Forms")]
        public IDictionary<string, IList<FlowApiFillFormDescriptor>> Forms { get; set; }

    }
}
