// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// IntroText to be shown.
    /// </summary>
    public partial class FlowApiIntroTexts
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiIntroTexts class.
        /// </summary>
        public FlowApiIntroTexts() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiIntroTexts class.
        /// </summary>
        public FlowApiIntroTexts(IList<FlowApiText> texts = default(IList<FlowApiText>))
        {
            Texts = texts;
        }

        /// <summary>
        /// Collection of texts.
        /// </summary>
        [JsonProperty(PropertyName = "Texts")]
        public IList<FlowApiText> Texts { get; set; }

    }
}
