// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowPdfAttachmentDescriptor : FlowApiAddFormFieldDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the FlowPdfAttachmentDescriptor
        /// class.
        /// </summary>
        public FlowPdfAttachmentDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the FlowPdfAttachmentDescriptor
        /// class.
        /// </summary>
        public FlowPdfAttachmentDescriptor(string name = default(string), bool? readOnlyProperty = default(bool?), bool? required = default(bool?), double? x = default(double?), double? y = default(double?), double? width = default(double?), double? height = default(double?), int? page = default(int?), string type = default(string), string label = default(string))
            : base(name, readOnlyProperty, required, x, y, width, height, page, type)
        {
            Label = label;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Label")]
        public string Label { get; set; }

    }
}
