// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiSendEnvelopeBulkResult
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSendEnvelopeBulkResult
        /// class.
        /// </summary>
        public FlowApiSendEnvelopeBulkResult() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSendEnvelopeBulkResult
        /// class.
        /// </summary>
        public FlowApiSendEnvelopeBulkResult(IList<FlowApiSendEnvelopeBulkResultEntry> envelopeIds = default(IList<FlowApiSendEnvelopeBulkResultEntry>), string bulkId = default(string))
        {
            EnvelopeIds = envelopeIds;
            BulkId = bulkId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EnvelopeIds")]
        public IList<FlowApiSendEnvelopeBulkResultEntry> EnvelopeIds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BulkId")]
        public string BulkId { get; set; }

    }
}
