// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiFillListBoxFormDescriptor : FlowApiFillFormDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFillListBoxFormDescriptor
        /// class.
        /// </summary>
        public FlowApiFillListBoxFormDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFillListBoxFormDescriptor
        /// class.
        /// </summary>
        public FlowApiFillListBoxFormDescriptor(string name = default(string), string type = default(string), IList<string> selectedItems = default(IList<string>))
            : base(name, type)
        {
            SelectedItems = selectedItems;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SelectedItems")]
        public IList<string> SelectedItems { get; set; }

    }
}
