// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Options for the draft creation.
    /// </summary>
    public partial class FlowApiCreateDraftOptions
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiCreateDraftOptions class.
        /// </summary>
        public FlowApiCreateDraftOptions() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiCreateDraftOptions class.
        /// </summary>
        public FlowApiCreateDraftOptions(string afterSendRedirectUrl = default(string), string afterSendCallbackUrl = default(string), string redirectPolicy = default(string), bool? allowAgentRedirect = default(bool?), string iframeWhiteList = default(string))
        {
            AfterSendRedirectUrl = afterSendRedirectUrl;
            AfterSendCallbackUrl = afterSendCallbackUrl;
            RedirectPolicy = redirectPolicy;
            AllowAgentRedirect = allowAgentRedirect;
            IframeWhiteList = iframeWhiteList;
        }

        /// <summary>
        /// The redirection URL after sending the envelope.
        /// </summary>
        [JsonProperty(PropertyName = "AfterSendRedirectUrl")]
        public string AfterSendRedirectUrl { get; set; }

        /// <summary>
        /// The URL where a callbackl is sent to after sending the envelope.
        /// </summary>
        [JsonProperty(PropertyName = "AfterSendCallbackUrl")]
        public string AfterSendCallbackUrl { get; set; }

        /// <summary>
        /// Specifies where to redirect if
        /// &lt;code&gt;AllowAgentRedirect&lt;/code&gt; is
        /// &lt;code&gt;true&lt;/code&gt;. Possible values include: 'None',
        /// 'ToRecipients', 'ToDesigner', 'ToSend'
        /// </summary>
        [JsonProperty(PropertyName = "RedirectPolicy")]
        public string RedirectPolicy { get; set; }

        /// <summary>
        /// Specifies if the agentmode is active.
        /// </summary>
        [JsonProperty(PropertyName = "AllowAgentRedirect")]
        public bool? AllowAgentRedirect { get; set; }

        /// <summary>
        /// A string indicating a white list of urls where the designer is
        /// allowed to be used in agent mode.
        /// Example: "http://172.16.17.181;http://foo.org"
        /// </summary>
        [JsonProperty(PropertyName = "IframeWhiteList")]
        public string IframeWhiteList { get; set; }

    }
}
