// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Occurred warnings of an recipient.
    /// </summary>
    public partial class FlowApiEnvelopeStatusWarning
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiEnvelopeStatusWarning
        /// class.
        /// </summary>
        public FlowApiEnvelopeStatusWarning() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiEnvelopeStatusWarning
        /// class.
        /// </summary>
        public FlowApiEnvelopeStatusWarning(string type = default(string), IList<string> contentXmlList = default(IList<string>))
        {
            Type = type;
            ContentXmlList = contentXmlList;
        }

        /// <summary>
        /// The warning type. Possible values include: 'None',
        /// 'LongLivedDisposableCertificateUsage'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// The warning contents.
        /// </summary>
        [JsonProperty(PropertyName = "ContentXmlList")]
        public IList<string> ContentXmlList { get; set; }

    }
}
