// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Uses  UserIds as authentication method.
    /// </summary>
    public partial class FlowApiAuthenticationMethodUserId : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodUserId class.
        /// </summary>
        public FlowApiAuthenticationMethodUserId() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodUserId class.
        /// </summary>
        public FlowApiAuthenticationMethodUserId(string provider = default(string), IList<string> userIds = default(IList<string>))
            : base(provider)
        {
            UserIds = userIds;
        }

        /// <summary>
        /// The list of userids that are allowed to access the document.
        /// </summary>
        [JsonProperty(PropertyName = "UserIds")]
        public IList<string> UserIds { get; set; }

    }
}
