// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Picture SigType.
    /// </summary>
    public partial class FlowApiSigTypePicture : FlowApiSigType
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypePicture class.
        /// </summary>
        public FlowApiSigTypePicture() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypePicture class.
        /// </summary>
        public FlowApiSigTypePicture(string id = default(string), string type = default(string), bool? preferred = default(bool?), string allowedCapturingMethod = default(string), FlowApiStampImprintConfiguration stampImprintConfiguration = default(FlowApiStampImprintConfiguration))
            : base(id, type, preferred)
        {
            AllowedCapturingMethod = allowedCapturingMethod;
            StampImprintConfiguration = stampImprintConfiguration;
        }

        /// <summary>
        /// List of allowed capturing methods. Possible values include:
        /// 'Click2Sign', 'Draw2Sign', 'Type2Sign'
        /// </summary>
        [JsonProperty(PropertyName = "AllowedCapturingMethod")]
        public string AllowedCapturingMethod { get; set; }

        /// <summary>
        /// Confiugre StampImprintConfiguration.
        /// </summary>
        [JsonProperty(PropertyName = "StampImprintConfiguration")]
        public FlowApiStampImprintConfiguration StampImprintConfiguration { get; set; }

    }
}
