// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Authentication via certificate.
    /// </summary>
    public partial class FlowApiAuthenticationMethodCertificate : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodCertificate class.
        /// </summary>
        public FlowApiAuthenticationMethodCertificate() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodCertificate class.
        /// </summary>
        public FlowApiAuthenticationMethodCertificate(string provider = default(string), FlowApiCertificateFilter certificateFilter = default(FlowApiCertificateFilter))
            : base(provider)
        {
            CertificateFilter = certificateFilter;
        }

        /// <summary>
        /// Certificate filter for authentication.
        /// </summary>
        [JsonProperty(PropertyName = "CertificateFilter")]
        public FlowApiCertificateFilter CertificateFilter { get; set; }

    }
}
