// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Base class Form of a FormGroup.
    /// </summary>
    public partial class FlowApiForm
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiForm class.
        /// </summary>
        public FlowApiForm() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiForm class.
        /// </summary>
        public FlowApiForm(string id = default(string), int? positionPage = default(int?), int? docRefNumber = default(int?), FlowApiPosition position = default(FlowApiPosition), FlowApiSize size = default(FlowApiSize), bool? isHidden = default(bool?), string exportValue = default(string), string description = default(string), bool? keepExistingValue = default(bool?), int? customOrder = default(int?), string formType = default(string))
        {
            Id = id;
            PositionPage = positionPage;
            DocRefNumber = docRefNumber;
            Position = position;
            Size = size;
            IsHidden = isHidden;
            ExportValue = exportValue;
            Description = description;
            KeepExistingValue = keepExistingValue;
            CustomOrder = customOrder;
            FormType = formType;
        }

        /// <summary>
        /// Identifier for the form.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Page number for the form.
        /// </summary>
        [JsonProperty(PropertyName = "PositionPage")]
        public int? PositionPage { get; set; }

        /// <summary>
        /// Document number for the form.
        /// </summary>
        [JsonProperty(PropertyName = "DocRefNumber")]
        public int? DocRefNumber { get; set; }

        /// <summary>
        /// Exact position of the form.
        /// </summary>
        [JsonProperty(PropertyName = "Position")]
        public FlowApiPosition Position { get; set; }

        /// <summary>
        /// Width and Height of the object.
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public FlowApiSize Size { get; set; }

        /// <summary>
        /// Define if it is hidden.
        /// </summary>
        [JsonProperty(PropertyName = "IsHidden")]
        public bool? IsHidden { get; set; }

        /// <summary>
        /// The export value of the form field.
        /// </summary>
        [JsonProperty(PropertyName = "ExportValue")]
        public string ExportValue { get; set; }

        /// <summary>
        /// Description to provide details about the element.
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// If true, form value from Pdf is used.
        /// </summary>
        [JsonProperty(PropertyName = "KeepExistingValue")]
        public bool? KeepExistingValue { get; set; }

        /// <summary>
        /// Increasing order number. Can be used for tabbing through the form
        /// elements.
        /// </summary>
        [JsonProperty(PropertyName = "CustomOrder")]
        public int? CustomOrder { get; private set; }

        /// <summary>
        /// Define the type of the form. Possible values include: 'Unkown',
        /// 'CheckBox', 'ComboBox', 'ListBox', 'RadioButton', 'TextBox'
        /// </summary>
        [JsonProperty(PropertyName = "FormType")]
        public string FormType { get; set; }

    }
}
