// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Configure the SigningCertificateDescriptor.
    /// </summary>
    public partial class FlowApiSigningCertificateDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSigningCertificateDescriptor class.
        /// </summary>
        public FlowApiSigningCertificateDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSigningCertificateDescriptor class.
        /// </summary>
        public FlowApiSigningCertificateDescriptor(string identifier = default(string), string type = default(string), string csp = default(string))
        {
            Identifier = identifier;
            Type = type;
            Csp = csp;
        }

        /// <summary>
        /// Identifier for this SigningCertificateDescriptor.
        /// </summary>
        [JsonProperty(PropertyName = "Identifier")]
        public string Identifier { get; set; }

        /// <summary>
        /// Defines which type should be used. Possible values include:
        /// 'Sha1Thumbprint', 'Subject'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// Defines which Csp type should be used. Possible values include:
        /// 'Default', 'Custom'
        /// </summary>
        [JsonProperty(PropertyName = "Csp")]
        public string Csp { get; set; }

    }
}
