// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiAddFormFieldWithFontSettingsDescriptor : FlowApiAddFormFieldDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAddFormFieldWithFontSettingsDescriptor class.
        /// </summary>
        public FlowApiAddFormFieldWithFontSettingsDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAddFormFieldWithFontSettingsDescriptor class.
        /// </summary>
        public FlowApiAddFormFieldWithFontSettingsDescriptor(string name = default(string), bool? readOnlyProperty = default(bool?), bool? required = default(bool?), double? x = default(double?), double? y = default(double?), double? width = default(double?), double? height = default(double?), int? page = default(int?), string type = default(string), string textColor = default(string), double? fontSize = default(double?), string fontName = default(string), bool? bold = default(bool?), bool? italic = default(bool?), string textAlign = default(string))
            : base(name, readOnlyProperty, required, x, y, width, height, page, type)
        {
            TextColor = textColor;
            FontSize = fontSize;
            FontName = fontName;
            Bold = bold;
            Italic = italic;
            TextAlign = textAlign;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TextColor")]
        public string TextColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FontSize")]
        public double? FontSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FontName")]
        public string FontName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Bold")]
        public bool? Bold { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Italic")]
        public bool? Italic { get; set; }

        /// <summary>
        /// Possible values include: 'Left', 'Center', 'Right'
        /// </summary>
        [JsonProperty(PropertyName = "TextAlign")]
        public string TextAlign { get; set; }

    }
}
