// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Text element.
    /// </summary>
    public partial class FlowApiText
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiText class.
        /// </summary>
        public FlowApiText() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiText class.
        /// </summary>
        public FlowApiText(string language = default(string), string value = default(string))
        {
            Language = language;
            Value = value;
        }

        /// <summary>
        /// Language of this text.
        /// </summary>
        [JsonProperty(PropertyName = "Language")]
        public string Language { get; set; }

        /// <summary>
        /// Text of this element.
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
