// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Method to authenticate.
    /// </summary>
    public partial class FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiAuthenticationMethod
        /// class.
        /// </summary>
        public FlowApiAuthenticationMethod() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiAuthenticationMethod
        /// class.
        /// </summary>
        public FlowApiAuthenticationMethod(string provider = default(string))
        {
            Provider = provider;
        }

        /// <summary>
        /// Provider type for the authentication method. Possible values
        /// include: 'Pin', 'Google', 'Facebook', 'WindowsLive', 'Sms',
        /// 'UserId', 'Certificate', 'IdentityServer',
        /// 'NamirialRemoteSignature', 'GenericOAuthProvider',
        /// 'GenericSamlProvider'
        /// </summary>
        [JsonProperty(PropertyName = "Provider")]
        public string Provider { get; set; }

    }
}
