// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Authentication with Facebook.
    /// </summary>
    public partial class FlowApiAuthenticationMethodFacebook : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodFacebook class.
        /// </summary>
        public FlowApiAuthenticationMethodFacebook() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodFacebook class.
        /// </summary>
        public FlowApiAuthenticationMethodFacebook(string provider = default(string))
            : base(provider)
        {
        }

    }
}
