// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Signature task.
    /// </summary>
    public partial class FlowApiSignature : FlowApiWorkstepTask
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSignature class.
        /// </summary>
        public FlowApiSignature() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSignature class.
        /// </summary>
        public FlowApiSignature(bool? isEnabled = default(bool?), bool? isCompleted = default(bool?), bool? isRequired = default(bool?), string id = default(string), string displayName = default(string), int? docRefNumber = default(int?), string additionalInformation = default(string), string completedDataTime = default(string), string batchId = default(string), string taskType = default(string), int? positionPage = default(int?), FlowApiPosition position = default(FlowApiPosition), FlowApiSize size = default(FlowApiSize), IList<KeyValuePairStringString> additionalParameters = default(IList<KeyValuePairStringString>), IList<FlowApiSigType> allowedSignatureTypes = default(IList<FlowApiSigType>), string additionalClientInformation = default(string))
            : base(isEnabled, isCompleted, isRequired, id, displayName, docRefNumber, additionalInformation, completedDataTime, batchId, taskType)
        {
            PositionPage = positionPage;
            Position = position;
            Size = size;
            AdditionalParameters = additionalParameters;
            AllowedSignatureTypes = allowedSignatureTypes;
            AdditionalClientInformation = additionalClientInformation;
        }

        /// <summary>
        /// Page number of the signature.
        /// </summary>
        [JsonProperty(PropertyName = "PositionPage")]
        public int? PositionPage { get; set; }

        /// <summary>
        /// Exact position of the signature.
        /// </summary>
        [JsonProperty(PropertyName = "Position")]
        public FlowApiPosition Position { get; set; }

        /// <summary>
        /// Width and height of the signature.
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public FlowApiSize Size { get; set; }

        /// <summary>
        /// Collection of additional parameters, as KeyValue pair.
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalParameters")]
        public IList<KeyValuePairStringString> AdditionalParameters { get; set; }

        /// <summary>
        /// Collection of allowed SigTypes.
        /// </summary>
        [JsonProperty(PropertyName = "AllowedSignatureTypes")]
        public IList<FlowApiSigType> AllowedSignatureTypes { get; set; }

        /// <summary>
        /// Additional client information.
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalClientInformation")]
        public string AdditionalClientInformation { get; set; }

    }
}
