// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines a client action.
    /// </summary>
    public partial class FlowApiClientAction
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiClientAction class.
        /// </summary>
        public FlowApiClientAction() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiClientAction class.
        /// </summary>
        public FlowApiClientAction(string clientName, string action, bool? removeDocumentFromRecentDocumentList = default(bool?), bool? callClientActionOnlyAfterSuccessfulSync = default(bool?), bool? closeApp = default(bool?))
        {
            RemoveDocumentFromRecentDocumentList = removeDocumentFromRecentDocumentList;
            CallClientActionOnlyAfterSuccessfulSync = callClientActionOnlyAfterSuccessfulSync;
            ClientName = clientName;
            CloseApp = closeApp;
            Action = action;
        }

        /// <summary>
        /// Removes the document from recent document list.
        /// </summary>
        [JsonProperty(PropertyName = "RemoveDocumentFromRecentDocumentList")]
        public bool? RemoveDocumentFromRecentDocumentList { get; set; }

        /// <summary>
        /// Call client action only after successful sync.
        /// </summary>
        [JsonProperty(PropertyName = "CallClientActionOnlyAfterSuccessfulSync")]
        public bool? CallClientActionOnlyAfterSuccessfulSync { get; set; }

        /// <summary>
        /// Name for the client.
        /// </summary>
        [JsonProperty(PropertyName = "ClientName")]
        public string ClientName { get; set; }

        /// <summary>
        /// Defines if the app should be closed.
        /// </summary>
        [JsonProperty(PropertyName = "CloseApp")]
        public bool? CloseApp { get; set; }

        /// <summary>
        /// Url of the action.
        /// </summary>
        [JsonProperty(PropertyName = "Action")]
        public string Action { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (ClientName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "ClientName");
            }
            if (Action == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Action");
            }
        }
    }
}
