// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiTargetDocument
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiTargetDocument class.
        /// </summary>
        public FlowApiTargetDocument() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiTargetDocument class.
        /// </summary>
        public FlowApiTargetDocument(int docRefNumber, bool? isCompleted = default(bool?))
        {
            DocRefNumber = docRefNumber;
            IsCompleted = isCompleted;
        }

        /// <summary>
        /// Document number.
        /// </summary>
        [JsonProperty(PropertyName = "DocRefNumber")]
        public int DocRefNumber { get; set; }

        /// <summary>
        /// Define if it is completed.
        /// </summary>
        [JsonProperty(PropertyName = "IsCompleted")]
        public bool? IsCompleted { get; private set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
