// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Information about a forms group in this workstep.
    /// </summary>
    public partial class FlowApiFormGroup : FlowApiWorkstepTask
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFormGroup class.
        /// </summary>
        public FlowApiFormGroup() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFormGroup class.
        /// </summary>
        public FlowApiFormGroup(bool? isEnabled = default(bool?), bool? isCompleted = default(bool?), bool? isRequired = default(bool?), string id = default(string), string displayName = default(string), int? docRefNumber = default(int?), string additionalInformation = default(string), string completedDataTime = default(string), string batchId = default(string), string taskType = default(string), IList<FlowApiForm> forms = default(IList<FlowApiForm>))
            : base(isEnabled, isCompleted, isRequired, id, displayName, docRefNumber, additionalInformation, completedDataTime, batchId, taskType)
        {
            Forms = forms;
        }

        /// <summary>
        /// Lists all the form elements which are part of this group.
        /// </summary>
        [JsonProperty(PropertyName = "Forms")]
        public IList<FlowApiForm> Forms { get; set; }

    }
}
