// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Allows to define actions which will be executed when the workstep will
    /// be finished. Those actions are performed before the ServerAction will
    /// be called and, depending on the type of the action, it might change
    /// the documents according to the workstep!
    /// </summary>
    public partial class FlowApiFinalizeActions
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFinalizeActions class.
        /// </summary>
        public FlowApiFinalizeActions() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFinalizeActions class.
        /// </summary>
        public FlowApiFinalizeActions(IList<FlowApiFinalizeActionsTimestamp> timestamps = default(IList<FlowApiFinalizeActionsTimestamp>))
        {
            Timestamps = timestamps;
        }

        /// <summary>
        /// Collection of timestamps.
        /// </summary>
        [JsonProperty(PropertyName = "Timestamps")]
        public IList<FlowApiFinalizeActionsTimestamp> Timestamps { get; set; }

    }
}
