// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Base class WorkstepTask in WorkstepConfiguration.
    /// </summary>
    public partial class FlowApiWorkstepTask
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiWorkstepTask class.
        /// </summary>
        public FlowApiWorkstepTask() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiWorkstepTask class.
        /// </summary>
        public FlowApiWorkstepTask(bool? isEnabled = default(bool?), bool? isCompleted = default(bool?), bool? isRequired = default(bool?), string id = default(string), string displayName = default(string), int? docRefNumber = default(int?), string additionalInformation = default(string), string completedDataTime = default(string), string batchId = default(string), string taskType = default(string))
        {
            IsEnabled = isEnabled;
            IsCompleted = isCompleted;
            IsRequired = isRequired;
            Id = id;
            DisplayName = displayName;
            DocRefNumber = docRefNumber;
            AdditionalInformation = additionalInformation;
            CompletedDataTime = completedDataTime;
            BatchId = batchId;
            TaskType = taskType;
        }

        /// <summary>
        /// Define if the task is enabled.
        /// </summary>
        [JsonProperty(PropertyName = "IsEnabled")]
        public bool? IsEnabled { get; private set; }

        /// <summary>
        /// Define if the task is completed.
        /// </summary>
        [JsonProperty(PropertyName = "IsCompleted")]
        public bool? IsCompleted { get; private set; }

        /// <summary>
        /// Define if the task is required.
        /// </summary>
        [JsonProperty(PropertyName = "IsRequired")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// Define the identifier for the task.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// Define the name to be displayed.
        /// </summary>
        [JsonProperty(PropertyName = "DisplayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Document number of the task.
        /// </summary>
        [JsonProperty(PropertyName = "DocRefNumber")]
        public int? DocRefNumber { get; set; }

        /// <summary>
        /// Additional information for the client
        /// </summary>
        [JsonProperty(PropertyName = "AdditionalInformation")]
        public string AdditionalInformation { get; set; }

        /// <summary>
        /// If the task is completed the server date time the task was
        /// completed at in UTC.
        /// </summary>
        [JsonProperty(PropertyName = "CompletedDataTime")]
        public string CompletedDataTime { get; private set; }

        /// <summary>
        /// Defines multiple tasks which can be executed as a batch (e.g.
        /// signatures which accept same data).
        /// </summary>
        [JsonProperty(PropertyName = "BatchId")]
        public string BatchId { get; set; }

        /// <summary>
        /// Type of the task. Possible values include: 'Unkown',
        /// 'FillFormsGroup', 'AddAttachment', 'SignField', 'AppendPages',
        /// 'ConfirmReading', 'ReadAgreement', 'AddPictureAnnotation',
        /// 'AddTypewriterAnnotation', 'SignPkcs7'
        /// </summary>
        [JsonProperty(PropertyName = "TaskType")]
        public string TaskType { get; set; }

    }
}
