// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Representation of s team member.
    /// </summary>
    public partial class FlowApiTeamMember
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiTeamMember class.
        /// </summary>
        public FlowApiTeamMember() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiTeamMember class.
        /// </summary>
        public FlowApiTeamMember(string email = default(string), IList<FlowApiTeamMember> members = default(IList<FlowApiTeamMember>))
        {
            Email = email;
            Members = members;
        }

        /// <summary>
        /// The email of the team member.
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// The team members which are one hiarchy step deeper.
        /// </summary>
        [JsonProperty(PropertyName = "Members")]
        public IList<FlowApiTeamMember> Members { get; set; }

    }
}
