// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Represents an envelope.
    /// </summary>
    public partial class FlowApiExtendedFindEnvelopesResultEntry
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiExtendedFindEnvelopesResultEntry class.
        /// </summary>
        public FlowApiExtendedFindEnvelopesResultEntry() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiExtendedFindEnvelopesResultEntry class.
        /// </summary>
        public FlowApiExtendedFindEnvelopesResultEntry(string status = default(string), string id = default(string), string name = default(string), string metaDataXml = default(string), string bulk = default(string))
        {
            Status = status;
            Id = id;
            Name = name;
            MetaDataXml = metaDataXml;
            Bulk = bulk;
        }

        /// <summary>
        /// The status of the envelope. Possible values include: 'Draft',
        /// 'Started', 'InProgress', 'Canceled', 'Completed', 'Expired',
        /// 'Rejected', 'Template', 'CompletedWithWarnings', 'BulkCompleted',
        /// 'BulkPartlyCompleted'
        /// </summary>
        [JsonProperty(PropertyName = "Status")]
        public string Status { get; set; }

        /// <summary>
        /// The envelope id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// The name of the envelope.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MetaDataXml")]
        public string MetaDataXml { get; set; }

        /// <summary>
        /// The bulk id.
        /// Only set if the envelope is part of a bulk.
        /// </summary>
        [JsonProperty(PropertyName = "Bulk")]
        public string Bulk { get; set; }

    }
}
