// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiUserInformation
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiUserInformation class.
        /// </summary>
        public FlowApiUserInformation() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiUserInformation class.
        /// </summary>
        public FlowApiUserInformation(string firstName = default(string), string lastName = default(string), string eMail = default(string))
        {
            FirstName = firstName;
            LastName = lastName;
            EMail = eMail;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EMail")]
        public string EMail { get; set; }

    }
}
