// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Configuration of WorkstepIdStamp.
    /// </summary>
    public partial class FlowApiWorkstepIdStampConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiWorkstepIdStampConfiguration class.
        /// </summary>
        public FlowApiWorkstepIdStampConfiguration() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiWorkstepIdStampConfiguration class.
        /// </summary>
        public FlowApiWorkstepIdStampConfiguration(string referenceCorner = default(string), string color = default(string), FlowApiWorkstepIdStampConfigurationLocation location = default(FlowApiWorkstepIdStampConfigurationLocation))
        {
            ReferenceCorner = referenceCorner;
            Color = color;
            Location = location;
        }

        /// <summary>
        /// Defines the corner to reference. Possible values include:
        /// 'Upper_Right', 'Upper_Left', 'Lower_Right', 'Lower_Left'
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceCorner")]
        public string ReferenceCorner { get; set; }

        /// <summary>
        /// Defines the color. (e.g. "blue")
        /// </summary>
        [JsonProperty(PropertyName = "Color")]
        public string Color { get; set; }

        /// <summary>
        /// Defines the location of this object.
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public FlowApiWorkstepIdStampConfigurationLocation Location { get; set; }

    }
}
