// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiSigTypeType2Sign : FlowApiSigTypePicture
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypeType2Sign class.
        /// </summary>
        public FlowApiSigTypeType2Sign() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypeType2Sign class.
        /// </summary>
        public FlowApiSigTypeType2Sign(string id = default(string), string type = default(string), bool? preferred = default(bool?), string allowedCapturingMethod = default(string), FlowApiStampImprintConfiguration stampImprintConfiguration = default(FlowApiStampImprintConfiguration))
            : base(id, type, preferred, allowedCapturingMethod, stampImprintConfiguration)
        {
        }

    }
}
