// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// TransactionCode SigType.
    /// </summary>
    public partial class FlowApiSigTypeTransactionCode : FlowApiSigType
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypeTransactionCode
        /// class.
        /// </summary>
        public FlowApiSigTypeTransactionCode() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSigTypeTransactionCode
        /// class.
        /// </summary>
        public FlowApiSigTypeTransactionCode(string id = default(string), string type = default(string), bool? preferred = default(bool?), string trModType = default(string), int? trValidityInSeconds = default(int?), string ly = default(string), string trConfIdIssueCertificate = default(string), string trConfId = default(string), bool? isPhoneNumberRequired = default(bool?))
            : base(id, type, preferred)
        {
            TrModType = trModType;
            TrValidityInSeconds = trValidityInSeconds;
            Ly = ly;
            TrConfIdIssueCertificate = trConfIdIssueCertificate;
            TrConfId = trConfId;
            IsPhoneNumberRequired = isPhoneNumberRequired;
        }

        /// <summary>
        /// Transaction code modul type.
        /// </summary>
        [JsonProperty(PropertyName = "TrModType")]
        public string TrModType { get; set; }

        /// <summary>
        /// Validation of transaction in seconds.
        /// </summary>
        [JsonProperty(PropertyName = "TrValidityInSeconds")]
        public int? TrValidityInSeconds { get; set; }

        /// <summary>
        /// Layout of the transaction code.
        /// </summary>
        [JsonProperty(PropertyName = "Ly")]
        public string Ly { get; set; }

        /// <summary>
        /// Reference to transaction code configuration for issuing the
        /// certificate and signing.
        /// </summary>
        [JsonProperty(PropertyName = "TrConfIdIssueCertificate")]
        public string TrConfIdIssueCertificate { get; set; }

        /// <summary>
        /// Reference to transcation code configuration id for signing.
        /// </summary>
        [JsonProperty(PropertyName = "TrConfId")]
        public string TrConfId { get; set; }

        /// <summary>
        /// Define if the phonenumber should be required.
        /// </summary>
        [JsonProperty(PropertyName = "IsPhoneNumberRequired")]
        public bool? IsPhoneNumberRequired { get; set; }

    }
}
