// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Information about the recipient of the document.
    /// </summary>
    public partial class FlowApiReceiverInformation
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiReceiverInformation class.
        /// </summary>
        public FlowApiReceiverInformation() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiReceiverInformation class.
        /// </summary>
        public FlowApiReceiverInformation(FlowApiUserInformation userInformation = default(FlowApiUserInformation), string holderInformation = default(string), FlowApiDisposableCertificateDisclaimerTexts disposableCertificateDisclaimerTexts = default(FlowApiDisposableCertificateDisclaimerTexts))
        {
            UserInformation = userInformation;
            HolderInformation = holderInformation;
            DisposableCertificateDisclaimerTexts = disposableCertificateDisclaimerTexts;
        }

        /// <summary>
        /// Information about the user.
        /// </summary>
        [JsonProperty(PropertyName = "UserInformation")]
        public FlowApiUserInformation UserInformation { get; set; }

        /// <summary>
        /// Information about the holder.
        /// </summary>
        [JsonProperty(PropertyName = "HolderInformation")]
        public string HolderInformation { get; set; }

        /// <summary>
        /// Disposable certificate disclaimer texts.
        /// </summary>
        [JsonProperty(PropertyName = "DisposableCertificateDisclaimerTexts")]
        public FlowApiDisposableCertificateDisclaimerTexts DisposableCertificateDisclaimerTexts { get; set; }

    }
}
