// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiExtendedFindUsersResultEntry
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiExtendedFindUsersResultEntry class.
        /// </summary>
        public FlowApiExtendedFindUsersResultEntry() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiExtendedFindUsersResultEntry class.
        /// </summary>
        public FlowApiExtendedFindUsersResultEntry(string id = default(string), string email = default(string), string firstName = default(string), string lastName = default(string), string userName = default(string), string sid = default(string), string role = default(string), bool? isUserManager = default(bool?), bool? isEnabled = default(bool?), IList<FlowApiUserAuthentication> authentications = default(IList<FlowApiUserAuthentication>))
        {
            Id = id;
            Email = email;
            FirstName = firstName;
            LastName = lastName;
            UserName = userName;
            Sid = sid;
            Role = role;
            IsUserManager = isUserManager;
            IsEnabled = isEnabled;
            Authentications = authentications;
        }

        /// <summary>
        /// The id of the User.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id { get; set; }

        /// <summary>
        /// The email address of the User.
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// The first name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// The last name of the user.
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// username of the user (used for usersynchronisation and alternative
        /// logins)
        /// </summary>
        [JsonProperty(PropertyName = "UserName")]
        public string UserName { get; set; }

        /// <summary>
        /// sid of the user (used for usersynchronisation and alternative
        /// logins)
        /// </summary>
        [JsonProperty(PropertyName = "Sid")]
        public string Sid { get; set; }

        /// <summary>
        /// The role of the user, which defines its permissions. Possible
        /// values include: 'None', 'PowerUser', 'RegisteredSigner'
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

        /// <summary>
        /// Defines if the user can manage other users (add/delete/modify).
        /// </summary>
        [JsonProperty(PropertyName = "IsUserManager")]
        public bool? IsUserManager { get; set; }

        /// <summary>
        /// Defines if the user is enabled and allowed to use the system.
        /// </summary>
        [JsonProperty(PropertyName = "IsEnabled")]
        public bool? IsEnabled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Authentications")]
        public IList<FlowApiUserAuthentication> Authentications { get; set; }

    }
}
