// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// A template for signature definitions.
    /// </summary>
    public partial class FlowApiSigTemplate
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSigTemplate class.
        /// </summary>
        public FlowApiSigTemplate() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSigTemplate class.
        /// </summary>
        public FlowApiSigTemplate(FlowApiSize size = default(FlowApiSize), IList<FlowApiSigType> allowedSignatureTypes = default(IList<FlowApiSigType>))
        {
            Size = size;
            AllowedSignatureTypes = allowedSignatureTypes;
        }

        /// <summary>
        /// Define width and height of the elements.
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public FlowApiSize Size { get; set; }

        /// <summary>
        /// Allowed signatures types.
        /// </summary>
        [JsonProperty(PropertyName = "AllowedSignatureTypes")]
        public IList<FlowApiSigType> AllowedSignatureTypes { get; set; }

    }
}
