// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Signatureplugin certificate filter configuration.
    /// </summary>
    public partial class FlowApiCertificateFilter
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiCertificateFilter class.
        /// </summary>
        public FlowApiCertificateFilter() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiCertificateFilter class.
        /// </summary>
        public FlowApiCertificateFilter(IList<string> keyUsages = default(IList<string>), IList<string> thumbPrints = default(IList<string>), IList<string> rootThumbPrints = default(IList<string>))
        {
            KeyUsages = keyUsages;
            ThumbPrints = thumbPrints;
            RootThumbPrints = rootThumbPrints;
        }

        /// <summary>
        /// KeyUsages.
        /// </summary>
        [JsonProperty(PropertyName = "KeyUsages")]
        public IList<string> KeyUsages { get; set; }

        /// <summary>
        /// ThumbPrints.
        /// </summary>
        [JsonProperty(PropertyName = "ThumbPrints")]
        public IList<string> ThumbPrints { get; set; }

        /// <summary>
        /// RootThumbPrints.
        /// </summary>
        [JsonProperty(PropertyName = "RootThumbPrints")]
        public IList<string> RootThumbPrints { get; set; }

    }
}
