// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Information about the sender.
    /// </summary>
    public partial class FlowApiSenderInformation
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSenderInformation class.
        /// </summary>
        public FlowApiSenderInformation() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSenderInformation class.
        /// </summary>
        public FlowApiSenderInformation(FlowApiUserInformation userInformation = default(FlowApiUserInformation))
        {
            UserInformation = userInformation;
        }

        /// <summary>
        /// Information about the user.
        /// </summary>
        [JsonProperty(PropertyName = "UserInformation")]
        public FlowApiUserInformation UserInformation { get; set; }

    }
}
