// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Descriptor to filter users.
    /// </summary>
    public partial class FlowApiFindUsersDescriptor
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFindUsersDescriptor class.
        /// </summary>
        public FlowApiFindUsersDescriptor() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFindUsersDescriptor class.
        /// </summary>
        public FlowApiFindUsersDescriptor(string role = default(string), bool? isUserManager = default(bool?))
        {
            Role = role;
            IsUserManager = isUserManager;
        }

        /// <summary>
        /// If set, filters by user role. Possible values include: 'None',
        /// 'PowerUser', 'RegisteredSigner'
        /// </summary>
        [JsonProperty(PropertyName = "Role")]
        public string Role { get; set; }

        /// <summary>
        /// If set, filters if the user manager flag is set.
        /// </summary>
        [JsonProperty(PropertyName = "IsUserManager")]
        public bool? IsUserManager { get; set; }

    }
}
