// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// abstract base class for defining authentication methods for users
    /// </summary>
    public partial class FlowApiUserAuthentication
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiUserAuthentication class.
        /// </summary>
        public FlowApiUserAuthentication() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiUserAuthentication class.
        /// </summary>
        public FlowApiUserAuthentication(string type = default(string), string discriminatorType = default(string))
        {
            Type = type;
            DiscriminatorType = discriminatorType;
        }

        /// <summary>
        /// defines the type of authentication. Possible values include: 'Saml'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; private set; }

        /// <summary>
        /// Property for parsing abstract base classes (polymorphism) in auto
        /// generated Swagger code.
        /// </summary>
        [JsonProperty(PropertyName = "DiscriminatorType")]
        public string DiscriminatorType { get; set; }

    }
}
