// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Authentication with generic Saml.
    /// </summary>
    public partial class FlowApiAuthenticationMethodGenericSamlClient : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodGenericSamlClient class.
        /// </summary>
        public FlowApiAuthenticationMethodGenericSamlClient() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodGenericSamlClient class.
        /// </summary>
        public FlowApiAuthenticationMethodGenericSamlClient(string provider = default(string), string providerIdentifier = default(string), IList<FlowApiAuthenticationMethodCheck> checks = default(IList<FlowApiAuthenticationMethodCheck>), IList<KeyValuePairStringString> fields = default(IList<KeyValuePairStringString>))
            : base(provider)
        {
            ProviderIdentifier = providerIdentifier;
            Checks = checks;
            Fields = fields;
        }

        /// <summary>
        /// Provider identifier.
        /// </summary>
        [JsonProperty(PropertyName = "ProviderIdentifier")]
        public string ProviderIdentifier { get; set; }

        /// <summary>
        /// Checks for the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "Checks")]
        public IList<FlowApiAuthenticationMethodCheck> Checks { get; set; }

        /// <summary>
        /// Fields for the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "Fields")]
        public IList<KeyValuePairStringString> Fields { get; set; }

    }
}
