// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// FormFieldValidation for emails.
    /// </summary>
    public partial class FlowApiFormFieldValidationEmail : FlowApiFormFieldValidation
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiFormFieldValidationEmail
        /// class.
        /// </summary>
        public FlowApiFormFieldValidationEmail() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiFormFieldValidationEmail
        /// class.
        /// </summary>
        public FlowApiFormFieldValidationEmail(string type = default(string))
            : base(type)
        {
        }

    }
}
