// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Authentication for a recipient.
    /// </summary>
    public partial class FlowApiSendEnvelopeAuthentication
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSendEnvelopeAuthentication class.
        /// </summary>
        public FlowApiSendEnvelopeAuthentication() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiSendEnvelopeAuthentication class.
        /// </summary>
        public FlowApiSendEnvelopeAuthentication(string method = default(string), string parameter = default(string), IList<FlowApiSendEnvelopeAuthenticationFilter> filters = default(IList<FlowApiSendEnvelopeAuthenticationFilter>))
        {
            Method = method;
            Parameter = parameter;
            Filters = filters;
        }

        /// <summary>
        /// The authentication method. Possible values include: 'Pin', 'Sms',
        /// 'WindowsLive', 'CustomOAuthProvider', 'CustomSamlProvider'
        /// </summary>
        [JsonProperty(PropertyName = "Method")]
        public string Method { get; set; }

        /// <summary>
        /// The needed parameters for the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "Parameter")]
        public string Parameter { get; set; }

        /// <summary>
        /// The filters for the authentication (OAUTH and SAML only).
        /// </summary>
        [JsonProperty(PropertyName = "Filters")]
        public IList<FlowApiSendEnvelopeAuthenticationFilter> Filters { get; set; }

    }
}
