// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Authentication with NamirialRemoteSignature.
    /// </summary>
    public partial class FlowApiAuthenticationMethodNamirialRemoteSignature : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodNamirialRemoteSignature class.
        /// </summary>
        public FlowApiAuthenticationMethodNamirialRemoteSignature() { }

        /// <summary>
        /// Initializes a new instance of the
        /// FlowApiAuthenticationMethodNamirialRemoteSignature class.
        /// </summary>
        public FlowApiAuthenticationMethodNamirialRemoteSignature(string provider = default(string), string deviceId = default(string), string userId = default(string))
            : base(provider)
        {
            DeviceId = deviceId;
            UserId = userId;
        }

        /// <summary>
        /// Device identifier.
        /// </summary>
        [JsonProperty(PropertyName = "DeviceId")]
        public string DeviceId { get; set; }

        /// <summary>
        /// User identifier.
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

    }
}
