// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiSentDocument
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiSentDocument class.
        /// </summary>
        public FlowApiSentDocument() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiSentDocument class.
        /// </summary>
        public FlowApiSentDocument(IList<FlowApiSize> pageSizesInPoints = default(IList<FlowApiSize>), int? docRefNumber = default(int?), string fileName = default(string), IList<FlowApiDocumentFormField> formFields = default(IList<FlowApiDocumentFormField>))
        {
            PageSizesInPoints = pageSizesInPoints;
            DocRefNumber = docRefNumber;
            FileName = fileName;
            FormFields = formFields;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PageSizesInPoints")]
        public IList<FlowApiSize> PageSizesInPoints { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DocRefNumber")]
        public int? DocRefNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FormFields")]
        public IList<FlowApiDocumentFormField> FormFields { get; set; }

    }
}
