// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Uses sms authentication as authentication method.
    /// </summary>
    public partial class FlowApiAuthenticationMethodSms : FlowApiAuthenticationMethod
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiAuthenticationMethodSms
        /// class.
        /// </summary>
        public FlowApiAuthenticationMethodSms() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiAuthenticationMethodSms
        /// class.
        /// </summary>
        public FlowApiAuthenticationMethodSms(string provider = default(string), string code = default(string), string codeGenerationTime = default(string), string phonenumber = default(string), string transactionId = default(string))
            : base(provider)
        {
            Code = code;
            CodeGenerationTime = codeGenerationTime;
            Phonenumber = phonenumber;
            TransactionId = transactionId;
        }

        /// <summary>
        /// Code for the authentication.
        /// </summary>
        [JsonProperty(PropertyName = "Code")]
        public string Code { get; private set; }

        /// <summary>
        /// Time the code is generated.
        /// </summary>
        [JsonProperty(PropertyName = "CodeGenerationTime")]
        public string CodeGenerationTime { get; private set; }

        /// <summary>
        /// Phonenumber for authentication.
        /// </summary>
        [JsonProperty(PropertyName = "Phonenumber")]
        public string Phonenumber { get; set; }

        /// <summary>
        /// Defines the id of the transaction.
        /// </summary>
        [JsonProperty(PropertyName = "TransactionId")]
        public string TransactionId { get; private set; }

    }
}
