// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FlowApiExtendedFindUsersResult
    {
        /// <summary>
        /// Initializes a new instance of the FlowApiExtendedFindUsersResult
        /// class.
        /// </summary>
        public FlowApiExtendedFindUsersResult() { }

        /// <summary>
        /// Initializes a new instance of the FlowApiExtendedFindUsersResult
        /// class.
        /// </summary>
        public FlowApiExtendedFindUsersResult(IList<FlowApiExtendedFindUsersResultEntry> entries = default(IList<FlowApiExtendedFindUsersResultEntry>))
        {
            Entries = entries;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entries")]
        public IList<FlowApiExtendedFindUsersResultEntry> Entries { get; set; }

    }
}
