// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace eSaw.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines callbacks which are sent out from the WSC (WorkStepController).
    /// </summary>
    public partial class WorkstepEventCallback
    {
        /// <summary>
        /// Initializes a new instance of the WorkstepEventCallback class.
        /// </summary>
        public WorkstepEventCallback() { }

        /// <summary>
        /// Initializes a new instance of the WorkstepEventCallback class.
        /// </summary>
        public WorkstepEventCallback(string url = default(string), IList<string> blacklist = default(IList<string>), IList<string> whiteList = default(IList<string>))
        {
            Url = url;
            Blacklist = blacklist;
            WhiteList = whiteList;
        }

        /// <summary>
        /// The callback URL.
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// A list off callback types which are NOT sent.
        /// An empty lists means are callback types should fire a callback.
        /// You can either have a black OR white list.
        /// </summary>
        [JsonProperty(PropertyName = "Blacklist")]
        public IList<string> Blacklist { get; set; }

        /// <summary>
        /// A list of callbacks which should be sent.
        /// An empty lists means are callback types should fire a callback.
        /// You can either have a black OR white list.
        /// </summary>
        [JsonProperty(PropertyName = "WhiteList")]
        public IList<string> WhiteList { get; set; }

    }
}
